### ISSUE TITLE
QA task list

### ISSUE THREAD

**Issue by someone235** [kaspanet/kaspad#2175]
The most important tasks for the next release are checkboxed, and the other ones are nice to have

- [x]  Sync node from scratch until it's synced
- [x] Restart node and wait until it's synced again
- [x] Stop node for an hour and start again. Restart towards the end of headers sync. Restart again towards the end of blocks sync. Restart in the middle of resolving virtual and wait until it's synced.
- [ ] Check basic wallet functionality - send and receive some KAS.
